#!/bin/sh
#
# This script is for AUTOMATIC INSTALLATION of LaTeX. It is meant to be used
# with Travis, Vagrant, etc. It is not recommended to install LaTeX on your
# machine with this script.
#
# Tämä skripti on tarkoitettu LaTeXin AUTOMAATTISEEN ASENTAMISEEN. Tämä ei ole
# suositeltava tapa asentaa LaTeX

DEPENDENCIES=""

while read DEP
do
  DEPENDENCIES="$DEPENDENCIES $DEP"
done < "dependencies_latex"

mkdir latex-install-tmp
cd latex-install-tmp

wget http://bay.uchicago.edu/tex-archive/systems/texlive/tlnet/install-tl-unx.tar.gz
tar -xzf install-tl-unx.tar.gz
sudo ./install-tl-*/install-tl --profile=../commons/latex-install-scripts/texlive.profile --repository=http://bay.uchicago.edu/tex-archive/systems/texlive/tlnet/
sudo /usr/local/texlive/2014/bin/x86_64-linux/tlmgr --repository=http://bay.uchicago.edu/tex-archive/systems/texlive/tlnet/ install $DEPENDENCIES
